name: CI - Build Scan Push

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show commit info
        run: |
          echo "Commit SHA: $GITHUB_SHA"
          echo "Repository: $GITHUB_REPOSITORY"
      - name: Set image tag variables
        id: vars
        run: |
          echo "SHA_SHORT=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "IMAGE_NAME=${{ secrets.DOCKERHUB_USERNAME }}/infospherre-frontend" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build \
            -t $IMAGE_NAME:$SHA_SHORT \
            -t $IMAGE_NAME:latest \
            .
      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ env.IMAGE_NAME }}:${{ env.SHA_SHORT }}
          severity: HIGH,CRITICAL
          exit-code: 1
          format: table

      - name: Run Trivy vulnerability scan
        run: |
          trivy image \
            --exit-code 1 \
            --severity HIGH,CRITICAL \
            $IMAGE_NAME:$SHA_SHORT

